"""empty message

Revision ID: 549151c086a6
Revises: 
Create Date: 2019-10-15 14:00:30.065930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549151c086a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_url', sa.String(length=2000), nullable=True),
    sa.Column('trimmed_url', sa.String(length=50), nullable=True),
    sa.Column('stats', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_long_url'), 'url', ['long_url'], unique=True)
    op.create_index(op.f('ix_url_trimmed_url'), 'url', ['trimmed_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_trimmed_url'), table_name='url')
    op.drop_index(op.f('ix_url_long_url'), table_name='url')
    op.drop_table('url')
    # ### end Alembic commands ###
